name = "zola-portfolio"
description = "One page portfolio developer website. Made with tailwindcss"
license = "MIT"
homepage = "https://github.com/sudipghimire533/zola-portfolio"
# The minimum version of Zola required
min_version = "0.14.0"
# An optional live demo URL
demo = "https://me.sudipg.com.np"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Sudip Ghimire"
homepage = "https://me.sudipg.com.np"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "Sudip Ghimire"
homepage = "https://me.sudipg.com.np"
repo = "https://github.com/sudipghimire533/zola-portfolio"
