name: Minimize tailwindcss
  
on:
  push:
    paths:
      - 'postcss.config.js'
      - 'tailwind.config.js'
      - 'templates/tailwind.css'
  workflow_dispatch:


jobs:
  purge_tailwind:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: 'production'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tailwind
        run: |
          npm install -D tailwindcss@latest postcss@latest autoprefixer@latest

      - name: Building
        run: npx tailwindcss -i templates/tailwind.css -c tailwind.config.js -o static/tailwind.css

      - name: Update local repo
        run: |
          git config --local user.name ${{ github.actor }}
          git add -f static/tailwind.css
          git commit -m "[post push] Generate optimized tailwindcss"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

